/*
 * FarmaCompara Paraguay — Datos Mock para MVP
 * Simula la respuesta del backend FastAPI
 */
import type { Farmacia, ProductoResumen, StatusScraping } from "@/types";

export const FARMACIAS_MOCK: (Farmacia & { color: string })[] = [
  {
    id: 1,
    nombre: "Punto Farma",
    slug: "punto_farma",
    logo_url: null,
    color: "#1B3A6B",
  },
  {
    id: 2,
    nombre: "Farmacenter",
    slug: "farmacenter",
    logo_url: null,
    color: "#059669",
  },
  {
    id: 3,
    nombre: "Biggie Farma",
    slug: "biggie_farma",
    logo_url: null,
    color: "#7C3AED",
  },
  {
    id: 4,
    nombre: "San Roque",
    slug: "san_roque",
    logo_url: null,
    color: "#DC2626",
  },
];

export const STATUS_MOCK: StatusScraping[] = [
  {
    farmacia: "Punto Farma",
    estado: "exitoso",
    ultimo_scraping: new Date().toISOString(),
    productos_indexados: 1842,
    errores: 0,
  },
  {
    farmacia: "Farmacenter",
    estado: "exitoso",
    ultimo_scraping: new Date(Date.now() - 86400000).toISOString(),
    productos_indexados: 2103,
    errores: 2,
  },
  {
    farmacia: "Biggie Farma",
    estado: "exitoso",
    ultimo_scraping: new Date().toISOString(),
    productos_indexados: 987,
    errores: 0,
  },
  {
    farmacia: "San Roque",
    estado: "pendiente",
    ultimo_scraping: null,
    productos_indexados: 0,
    errores: 0,
  },
];

export const PRODUCTOS_MOCK: ProductoResumen[] = [
  {
    id: 1,
    nombre_normalizado: "Ibuprofeno 400mg x 20 comprimidos",
    principio_activo: "Ibuprofeno",
    presentacion: "Comprimidos x 20",
    categoria: "Analgésicos",
    precio_minimo: 12500,
    farmacia_precio_minimo: "Punto Farma",
    ahorro_maximo: 5000,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 15000,
        precio_anterior: null,
        precio_promocional: 12500,
        porcentaje_descuento: 17,
        precio_efectivo: 12500,
        tiene_promocion: true,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[1],
        precio_actual: 17500,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 17500,
        tiene_promocion: false,
        url_producto: "https://farmacenter.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[2],
        precio_actual: 0,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 0,
        tiene_promocion: false,
        url_producto: "https://biggiefarma.com.py",
        imagen_url: null,
        disponible: false,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
  {
    id: 2,
    nombre_normalizado: "Paracetamol 500mg x 24 comprimidos",
    principio_activo: "Paracetamol",
    presentacion: "Comprimidos x 24",
    categoria: "Analgésicos",
    precio_minimo: 8900,
    farmacia_precio_minimo: "Biggie Farma",
    ahorro_maximo: 3100,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 11000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 11000,
        tiene_promocion: false,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[1],
        precio_actual: 10500,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 10500,
        tiene_promocion: false,
        url_producto: "https://farmacenter.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[2],
        precio_actual: 10000,
        precio_anterior: null,
        precio_promocional: 8900,
        porcentaje_descuento: 11,
        precio_efectivo: 8900,
        tiene_promocion: true,
        url_producto: "https://biggiefarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
  {
    id: 3,
    nombre_normalizado: "Omeprazol 20mg x 14 cápsulas",
    principio_activo: "Omeprazol",
    presentacion: "Cápsulas x 14",
    categoria: "Gastrointestinal",
    precio_minimo: 22000,
    farmacia_precio_minimo: "Farmacenter",
    ahorro_maximo: 8000,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 30000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 30000,
        tiene_promocion: false,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[1],
        precio_actual: 25000,
        precio_anterior: null,
        precio_promocional: 22000,
        porcentaje_descuento: 12,
        precio_efectivo: 22000,
        tiene_promocion: true,
        url_producto: "https://farmacenter.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[2],
        precio_actual: 27000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 27000,
        tiene_promocion: false,
        url_producto: "https://biggiefarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
  {
    id: 4,
    nombre_normalizado: "Amoxicilina 500mg x 21 cápsulas",
    principio_activo: "Amoxicilina",
    presentacion: "Cápsulas x 21",
    categoria: "Antibióticos",
    precio_minimo: 35000,
    farmacia_precio_minimo: "Punto Farma",
    ahorro_maximo: 12000,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 38000,
        precio_anterior: null,
        precio_promocional: 35000,
        porcentaje_descuento: 8,
        precio_efectivo: 35000,
        tiene_promocion: true,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[1],
        precio_actual: 47000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 47000,
        tiene_promocion: false,
        url_producto: "https://farmacenter.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[2],
        precio_actual: 42000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 42000,
        tiene_promocion: false,
        url_producto: "https://biggiefarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
  {
    id: 5,
    nombre_normalizado: "Loratadina 10mg x 10 comprimidos",
    principio_activo: "Loratadina",
    presentacion: "Comprimidos x 10",
    categoria: "Antialérgicos",
    precio_minimo: 9500,
    farmacia_precio_minimo: "Farmacenter",
    ahorro_maximo: 4500,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 14000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 14000,
        tiene_promocion: false,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[1],
        precio_actual: 11000,
        precio_anterior: null,
        precio_promocional: 9500,
        porcentaje_descuento: 14,
        precio_efectivo: 9500,
        tiene_promocion: true,
        url_producto: "https://farmacenter.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
  {
    id: 6,
    nombre_normalizado: "Metformina 850mg x 30 comprimidos",
    principio_activo: "Metformina",
    presentacion: "Comprimidos x 30",
    categoria: "Antidiabéticos",
    precio_minimo: 18500,
    farmacia_precio_minimo: "Biggie Farma",
    ahorro_maximo: 6500,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 25000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 25000,
        tiene_promocion: false,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[1],
        precio_actual: 22000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 22000,
        tiene_promocion: false,
        url_producto: "https://farmacenter.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[2],
        precio_actual: 20000,
        precio_anterior: null,
        precio_promocional: 18500,
        porcentaje_descuento: 8,
        precio_efectivo: 18500,
        tiene_promocion: true,
        url_producto: "https://biggiefarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
  {
    id: 7,
    nombre_normalizado: "Atorvastatina 20mg x 30 comprimidos",
    principio_activo: "Atorvastatina",
    presentacion: "Comprimidos x 30",
    categoria: "Cardiovascular",
    precio_minimo: 42000,
    farmacia_precio_minimo: "Punto Farma",
    ahorro_maximo: 18000,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 45000,
        precio_anterior: null,
        precio_promocional: 42000,
        porcentaje_descuento: 7,
        precio_efectivo: 42000,
        tiene_promocion: true,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[1],
        precio_actual: 60000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 60000,
        tiene_promocion: false,
        url_producto: "https://farmacenter.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
  {
    id: 8,
    nombre_normalizado: "Losartán 50mg x 30 comprimidos",
    principio_activo: "Losartán",
    presentacion: "Comprimidos x 30",
    categoria: "Cardiovascular",
    precio_minimo: 28000,
    farmacia_precio_minimo: "Biggie Farma",
    ahorro_maximo: 9000,
    precios: [
      {
        farmacia: FARMACIAS_MOCK[0],
        precio_actual: 37000,
        precio_anterior: null,
        precio_promocional: null,
        porcentaje_descuento: null,
        precio_efectivo: 37000,
        tiene_promocion: false,
        url_producto: "https://puntofarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
      {
        farmacia: FARMACIAS_MOCK[2],
        precio_actual: 30000,
        precio_anterior: null,
        precio_promocional: 28000,
        porcentaje_descuento: 7,
        precio_efectivo: 28000,
        tiene_promocion: true,
        url_producto: "https://biggiefarma.com.py",
        imagen_url: null,
        disponible: true,
        fecha_scraping: new Date().toISOString(),
      },
    ],
  },
];

export const BUSQUEDAS_POPULARES = [
  "Ibuprofeno",
  "Paracetamol",
  "Omeprazol",
  "Amoxicilina",
  "Loratadina",
  "Metformina",
  "Atorvastatina",
  "Losartán",
];

export const CATEGORIAS = [
  "Todos",
  "Analgésicos",
  "Antibióticos",
  "Antialérgicos",
  "Gastrointestinal",
  "Antidiabéticos",
  "Cardiovascular",
];

export function buscarEnMock(query: string): ProductoResumen[] {
  if (!query.trim()) return PRODUCTOS_MOCK;
  const q = query.toLowerCase().trim();
  return PRODUCTOS_MOCK.filter(
    (p) =>
      p.nombre_normalizado.toLowerCase().includes(q) ||
      (p.principio_activo?.toLowerCase().includes(q) ?? false) ||
      (p.categoria?.toLowerCase().includes(q) ?? false)
  );
}
